name: 'Push to a repo'
description: 'Github Action for pushing to a repo'
author: 'justjavac'
inputs:
  files:
    description: 'Newline-delimited list of path globs for asset files to upload'
    required: false
  fail_on_unmatched_files:
    description: 'Fails if any of the `files` globs match nothing. Defaults to false'
    required: false
  repository:
    description: 'Repository to make releases against, in <owner>/<repo> format'
    required: false
env:
  'GITHUB_TOKEN': 'As provided by Github Actions'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'green'
  icon: 'package'
